spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  doc:
    swagger-ui:
      path: /swagger-ui.html
    packagesToScan: ua.flowerista.shop.controllers
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: flowerista06@gmail.com
    password: nyjv qfzs hxmg zbkt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  data:
    redis:
      url: ${UPSTASH_REDIS_URL}

cloudinary:
  cloud-name: dg77kfpuv
  api-key: 296129768843992
  api-secret: P3pZAuh1vbr02UN1UpkkYouTg6g

security:
  jwt:
    secret-key: DC2AF6C498EDB7F7C7A284322F24FD66573D2A102D19FBE07C0E0D732E30A821
    expiration: ${JWT_AT_EXPIRATION:900000}
    refresh-token:
      expiration: ${JWT_RT_EXPIRATION:86400000}

jwt:
  cookie:
    expiration: ${JWT_COOKIE_EXPIRATION:86400000}

paypal:
  mode: sandbox
  client:
    id: AYbGfKxmmoO8dvZ5NjoGDHSdeiPwDHIQnEXIJh32YGtNu7m-0EDFHWDHj0mWwAobT6fr3gi-a5FfKlRn
    secret: ED-G7hOkeib9rSjTywLjrELqrTrEFAYVYYdwOA5XeocYZKoBnBOhN674w_dGnzdi9RZUsxcN0iW3Skmy

frontend:
  server:
    url: https://flowerista-frontend.vercel.app/

mapstruct:
  defaultComponentModel: spring
